### ISSUE TITLE
Loosen compatibility with StaticArrays

### ISSUE THREAD

**Issue by sethaxen** [mateuszbaran/HybridArrays.jl#12]
The current version specifier in `Project.toml` for StaticArrays is
```
StaticArrays = "=0.12.1"
```

which according to the [Pkg docs](https://julialang.github.io/Pkg.jl/v1/compatibility/index.html#Inequality-specifiers-1) constraints it exactly to that version. Can this restriction be loosened at all?

**Comment by mateuszbaran** [comment]
`HybridArrays` uses a few internal parts of `StaticArrays` so setting it to exactly that version was intentional. I'm just going to tag a new patch release each time a new version of `StaticArrays` is tagged. Just to make sure that everything works.

**Comment by sethaxen** [comment]
Okay, sounds good.
