### ISSUE TITLE
compability with DiffEq

### ISSUE THREAD

**Issue by SteffenPL** [mateuszbaran/HybridArrays.jl#18]
I posed an issue here about the use of HybridArrays for ODE problems:
https://github.com/SciML/ArrayInterface.jl/issues/58

(In short: It works already in some cases and is very fast; but a few things do not work out-of-the-box yet.)

Please close/delete this issue if it does not belong here...

**Comment by mateuszbaran** [comment]
Thanks for the report, I'll reply in the linked issue.
