### ISSUE TITLE
Why `StaticArrays = "=1.0.0"`?

### ISSUE THREAD

**Issue by chriselrod** [mateuszbaran/HybridArrays.jl#29]
Why can't we use `HybridArrays` alongside `StaticArrays` `v1.0.1`, for example?

**Comment by mateuszbaran** [comment]
`HybridArrays` does some type piracy of `StaticArrays` and heavily uses its internals so I decided to be on the safe side and require exactly the version I've verified. Maybe I'm too cautious here because so far I think only one patch release of `StaticArrays` broke `HybridArrays`.

**Comment by mateuszbaran** [comment]
For a long time there was no breakage from StaticArrays so HybridArrays 0.4.9 has a less strict version bound :slightly_smiling_face: .
