### ISSUE TITLE
combine_sizes not defined

### ISSUE THREAD

**Issue by judober** [mateuszbaran/HybridArrays.jl#50]
In combination with StaticArrays 1.4.2 I get the error `combine_sizes not defined` when comparing two matrices.
MWE:
```
A = HybridArray{Tuple{2,2,StaticArrays.Dynamic()}}(randn(2,2,4));

B = rand(2,2,4);

A .== B
```

Likely related:
https://github.com/JuliaArrays/StaticArrays.jl/pull/1008

**Comment by mateuszbaran** [comment]
Thanks for the report, I'll fix it in a moment.
