### ISSUE TITLE
Weak dependency without compat bound introduces a failure with ArrayInterface v7

### ISSUE THREAD

**Issue by kellertuer** [mateuszbaran/HybridArrays.jl#60]
The ArrayInterface 7.0 seems to be a mayor redesign since

https://github.com/JuliaManifolds/Manifolds.jl/actions/runs/4226233487/jobs/7339448739#step:5:725

can not import some parts?

**Comment by mateuszbaran** [comment]
It looks like HybridArrays will have to be updated for ArrayInterface v7.

**Comment by kellertuer** [comment]
seems to be resolved with the fix Chris did that caused the other error, see the log at

https://github.com/JuliaManifolds/Manifolds.jl/actions/runs/4226433589/jobs/7341000176#step:5:730
