### ISSUE TITLE
Cannot index HybridArray

### ISSUE THREAD

**Issue by judober** [mateuszbaran/HybridArrays.jl#65]
After updating to the newest StaticArrays (1.6.2), indexing a HybridArray seems not to be possible any more:
```
A = HybridArray{Tuple{2,2,StaticArrays.Dynamic()}}(randn(2,2,100));
A[1:2]
```
Throws a `MethodError: similar(::HybridArray{Tuple{2, 2, StaticArraysCore.Dynamic()}, Float64, 3, 3, Array{Float64, 3}}, ::Type{Float64}, ::Tuple{Base.OneTo{Int64}}) is ambiguous`

As it states similar, I think the problem is related to https://github.com/JuliaArrays/StaticArrays.jl/pull/1176. When downgrading to StaticArrays 1.6.1, it works.

**Comment by mateuszbaran** [comment]
Thanks for reporting it, I will fix it in a moment.
